name: Docker Nginx LAB
on:
    pull_request:
        types: [closed]
        branches: 
            - main

jobs:
    docker:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            # Checkout code
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Docker Login in DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            # Login to DockerHub
            - name: Build Docker Image
              run: docker build -t mynginx:latest .
            # Build Image
            - name: Docker Push
              run: docker push mynginx:latest
            # Test Image
            - name: Docker Image Test
              run: |
                    docker run -d -p 8080:80 --name test-nginx mynginx:test
                    sleep 5
                    curl http://localhost:8080 | grep "Hello from GitHub Actions"
                    docker stop test-nginx

            # Push Image
            - name: Docker Push to DockerHub
              run: |
               docker tag mynginx:latest ${{ secrets.DOCKERHUB_USERNAME }}/mynginx:latest
               docker push ${{ secrets.DOCKERHUB_USERNAME }}/mynginx:latest

               

